include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "lib/l10n/**"

linter:
  rules:
    unused_local_variable: ignore
    prefer_single_quotes: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_relative_lib_imports: true
    prefer_relative_imports: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_catching_errors: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    no_leading_underscores_for_library_prefixes: true
    avoid_bool_literals_in_conditional_expressions: true
    unnecessary_await_in_return: true
    camel_case_extensions: true
    camel_case_types: true
    avoid_positional_boolean_parameters: false
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    curly_braces_in_flow_control_structures: true
    file_names: true
    lines_longer_than_80_chars: false
    parameter_assignments: true
    prefer_final_in_for_each: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_mixin: true
    prefer_typing_uninitialized_variables: true
    sort_pub_dependencies: false
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    valid_regexps: true
    constant_identifier_names: true
    depend_on_referenced_packages: true
    prefer_interpolation_to_compose_strings: true
    library_private_types_in_public_api: true
    no_leading_underscores_for_local_identifiers: false
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    directives_ordering: true
    prefer_const_constructors: true
    sort_constructors_first: true
    # - avoid_print
