name: ios_design_system
description: iOS Design System.
version: 1.0.0
homepage:

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0
  flutter_svg: ^2.0.17
  gpt_markdown: ^1.0.16
  flutter_math_fork: ^0.7.3
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/src/assets_gen/
  assets:
    outputs:
      package_parameter_enabled: true
      class_name: Assets
  line_length: 80
  integrations:
    flutter_svg: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  fonts:
    - family: SF
      fonts:
        - asset: lib/src/assets/fonts/sf-pro-text-bold.ttf
          weight: 700
        - asset: lib/src/assets/fonts/sf-pro-text-semibold.ttf
          weight: 600
        - asset: lib/src/assets/fonts/sf-pro-text-medium.ttf
          weight: 500
        - asset: lib/src/assets/fonts/sf-pro-text-regular.ttf
          weight: 400

  assets:
    - lib/src/assets/svg/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
